### ISSUE TITLE
Help running apk analysis

### ISSUE THREAD

**Issue by louison** [marapapman/Violist#3]
Hi, 
I am looking to Violist since several days and I can't understand how I have to use the tool in order to make a correct analysis.
I would like to evaluate strings passed as arguments in specific method calls.
How can I use your tool to reach this goal ?

First of all, I can't manage to instrument any apk, the ./instrumentor.sh script always tells me that the output folder doesn't exist.
Secondly, I don't understant how I have to use Logger.repportString() in order to reach my objective.

Thank you very much for your help,

Best,
Louison

**Comment by winsonlyu** [comment]
Hi,
Please refer to the new version of Violist, https://github.com/USC-SQL/Violist
You can specify the target method calls and string arguments there.
